import { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import { generateSeoMetadata, StructuredData } from "@/components/SeoHead";

interface ChefLayoutProps {
  children: React.ReactNode;
  params: { chefSlugId: string };
}

/* generate metada */
export async function generateMetadata({
  params,
}: ChefLayoutProps): Promise<Metadata> {
  const { chefSlugId } = params;

  const [idPart] = chefSlugId.split(".");
  const chefId = idPart;

  try {
    const chef = await prisma.chef.findUnique({
      where: { id: chefId },
      include: {
        user: true,
      },
    });

    if (!chef) {
      return {
        title: "Chef non trovato",
        description: "Il profilo chef richiesto non esiste.",
      };
    }

    /* use data generated by gemini */
    if (chef.seoTitle && chef.seoDescription) {
      return generateSeoMetadata({
        // @ts-ignore
        seoTitle: chef.seoTitle,
        // @ts-ignore
        seoDescription: chef.seoDescription,
        // @ts-ignore
        seoKeywords: chef.seoKeywords,
        imageUrl: chef.coverUrl,
        url: `${process.env.NEXT_PUBLIC_APP_URL}/chef/${chefSlugId}`,
      });
    }

    /* fallback */
    const chefName = `${chef.user.firstname} ${chef.user.lastname}`;
    return generateSeoMetadata({
      seoTitle: `${chefName} - Chef Privato ${chef.city ? `a ${chef.city}` : ""}`,
      seoDescription:
        chef.bioBrief ||
        chef.bio ||
        `Scopri il profilo di ${chefName}, chef privato specializzato in cucina gourmet.`,
      imageUrl: chef.coverUrl,
      url: `${process.env.NEXT_PUBLIC_APP_URL}/chef/${chefSlugId}`,
    });
  } catch (error) {
    throw error;
    return {
      title: "Chef",
      description: "Profilo chef",
    };
  }
}

export default function ChefLayout({ children, params }: ChefLayoutProps) {
  return (
    <>
      {children}
      <ChefStructuredData chefSlugId={params.chefSlugId} />
    </>
  );
}

/* component to inject datas */
async function ChefStructuredData({ chefSlugId }: { chefSlugId: string }) {
  const [idPart] = chefSlugId.split(".");
  const chefId = idPart;

  try {
    const chef = await prisma.chef.findUnique({
      where: { id: chefId },
      select: {
        id: true,
        // @ts-ignore
        structuredData: true,
      },
    });

    // @ts-ignore
    if (!chef?.structuredData) return null;

    // @ts-ignore
    return <StructuredData data={chef.structuredData} />;
  } catch (error) {
    return null;
  }
}
